# Generated by Django 5.2.3 on 2026-01-20 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("location", models.CharField(max_length=200, verbose_name="位置")),
                (
                    "is_on_campus",
                    models.BooleanField(default=False, verbose_name="是否在校园内"),
                ),
                (
                    "price_min",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="最低价格(元/月)"
                    ),
                ),
                (
                    "price_max",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="最高价格(元/月)"
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("single_shared", "单间公共卫生间"),
                            ("single_private", "单间独立卫生间"),
                            ("one_bedroom", "一室一厅一卫"),
                            ("two_bedroom", "两室一厅一卫"),
                        ],
                        max_length=50,
                        verbose_name="房型",
                    ),
                ),
                ("area", models.CharField(max_length=50, verbose_name="面积")),
                (
                    "rental_status",
                    models.CharField(
                        choices=[
                            ("available", "可出租"),
                            ("rented", "已出租"),
                            ("reserved", "已预订"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="出租状态",
                    ),
                ),
                (
                    "available_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="最早可入住日期"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "has_air_conditioning",
                    models.BooleanField(default=False, verbose_name="空调"),
                ),
                (
                    "has_water_heater",
                    models.BooleanField(default=False, verbose_name="热水器"),
                ),
                (
                    "has_washing_machine",
                    models.BooleanField(default=False, verbose_name="洗衣机"),
                ),
                (
                    "has_refrigerator",
                    models.BooleanField(default=False, verbose_name="冰箱"),
                ),
                ("has_tv", models.BooleanField(default=False, verbose_name="电视")),
                ("has_wifi", models.BooleanField(default=False, verbose_name="WiFi")),
                ("has_bed", models.BooleanField(default=False, verbose_name="床")),
                ("has_desk", models.BooleanField(default=False, verbose_name="书桌")),
                (
                    "has_wardrobe",
                    models.BooleanField(default=False, verbose_name="衣柜"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "房源",
                "verbose_name_plural": "房源",
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="properties/", verbose_name="图片"),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="是否主图"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.property",
                        verbose_name="房源",
                    ),
                ),
            ],
            options={
                "verbose_name": "房源图片",
                "verbose_name_plural": "房源图片",
            },
        ),
    ]
