# Generated by Django 5.2.3 on 2025-06-17 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("location", models.CharField(max_length=200, verbose_name="位置")),
                (
                    "is_on_campus",
                    models.BooleanField(default=False, verbose_name="是否在校园内"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "price_unit",
                    models.CharField(
                        default="月", max_length=20, verbose_name="价格单位"
                    ),
                ),
                ("available_from", models.DateField(verbose_name="可入住日期")),
                ("room_type", models.CharField(max_length=50, verbose_name="房型")),
                ("area", models.CharField(max_length=50, verbose_name="面积")),
                ("description", models.TextField(verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "房源",
                "verbose_name_plural": "房源",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="联系人姓名")),
                ("phone", models.CharField(max_length=20, verbose_name="电话")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="properties.property",
                        verbose_name="房源",
                    ),
                ),
            ],
            options={
                "verbose_name": "联系人",
                "verbose_name_plural": "联系人",
            },
        ),
        migrations.CreateModel(
            name="PropertyFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="设施名称")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="properties.property",
                        verbose_name="房源",
                    ),
                ),
            ],
            options={
                "verbose_name": "房源设施",
                "verbose_name_plural": "房源设施",
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="properties/", verbose_name="图片"),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="是否主图"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.property",
                        verbose_name="房源",
                    ),
                ),
            ],
            options={
                "verbose_name": "房源图片",
                "verbose_name_plural": "房源图片",
            },
        ),
    ]
