# Generated by Django 5.2.3 on 2026-01-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="floor",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="楼层"
            ),
        ),
    ]
