# Generated by Django 5.2.3 on 2026-01-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_property_floor"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="bathroom_note",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="卫生间备注"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="bathroom_type",
            field=models.CharField(
                choices=[
                    ("private", "独立卫生间"),
                    ("shared", "公共卫生间"),
                    ("none", "无"),
                ],
                default="private",
                max_length=20,
                verbose_name="卫生间类型",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="electricity_fee",
            field=models.CharField(blank=True, max_length=200, verbose_name="电费"),
        ),
        migrations.AddField(
            model_name="property",
            name="gas_fee",
            field=models.CharField(blank=True, max_length=200, verbose_name="天然气费"),
        ),
        migrations.AddField(
            model_name="property",
            name="gender_restriction",
            field=models.CharField(
                choices=[
                    ("any", "不限性别"),
                    ("male", "仅限男生"),
                    ("female", "仅限女生"),
                ],
                default="any",
                max_length=20,
                verbose_name="性别限制",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="has_kitchen",
            field=models.BooleanField(default=False, verbose_name="厨房"),
        ),
        migrations.AddField(
            model_name="property",
            name="internet_fee",
            field=models.CharField(blank=True, max_length=200, verbose_name="网络费"),
        ),
        migrations.AddField(
            model_name="property",
            name="kitchen_note",
            field=models.CharField(blank=True, max_length=200, verbose_name="厨房备注"),
        ),
        migrations.AddField(
            model_name="property",
            name="misc_fee",
            field=models.CharField(blank=True, max_length=200, verbose_name="杂费"),
        ),
        migrations.AddField(
            model_name="property",
            name="property_fee",
            field=models.CharField(blank=True, max_length=200, verbose_name="物业费"),
        ),
        migrations.AddField(
            model_name="property",
            name="room_number",
            field=models.CharField(blank=True, max_length=100, verbose_name="房间号"),
        ),
        migrations.AddField(
            model_name="property",
            name="water_fee",
            field=models.CharField(blank=True, max_length=200, verbose_name="水费"),
        ),
        migrations.AddField(
            model_name="property",
            name="zone",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "芳菲阁A区"),
                    ("B", "芳菲阁B区"),
                    ("C", "芳菲阁C区"),
                    ("D", "芳菲阁D区"),
                    ("E", "芳菲阁E区"),
                    ("F", "芳菲阁F区"),
                    ("G", "芳菲阁G区"),
                    ("H", "芳菲阁H区"),
                ],
                max_length=10,
                verbose_name="位置分区",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="area",
            field=models.CharField(blank=True, max_length=50, verbose_name="面积"),
        ),
        migrations.AlterField(
            model_name="property",
            name="has_wifi",
            field=models.BooleanField(default=False, verbose_name="网络"),
        ),
        migrations.AlterField(
            model_name="property",
            name="location",
            field=models.CharField(max_length=200, verbose_name="具体位置"),
        ),
        migrations.AlterField(
            model_name="property",
            name="price_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="最高价格(元/月)",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="price_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="最低价格(元/月)",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("studio", "单身公寓"),
                    ("single", "单间"),
                    ("one_bedroom", "一室一厅"),
                    ("two_bedroom", "两室一厅"),
                    ("three_bedroom", "三室一厅"),
                    ("five_bedroom", "五室一厅"),
                ],
                max_length=50,
                verbose_name="房型",
            ),
        ),
    ]
