# Generated by Django 5.2.3 on 2026-01-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_property_bathroom_note_property_bathroom_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                ("phone", models.CharField(max_length=20, verbose_name="联系方式")),
                ("requirements", models.TextField(blank=True, verbose_name="房子要求")),
                (
                    "move_in_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="期望入住时间"
                    ),
                ),
                (
                    "price_min",
                    models.IntegerField(blank=True, null=True, verbose_name="价格下限"),
                ),
                (
                    "price_max",
                    models.IntegerField(blank=True, null=True, verbose_name="价格上限"),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="是否已处理"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
            ],
            options={
                "verbose_name": "客户咨询",
                "verbose_name_plural": "客户咨询",
                "ordering": ["-created_at"],
            },
        ),
    ]
